### ISSUE TITLE
执行 npm run dev 报错了，帮忙看看怎么回事

### ISSUE THREAD

**Issue by lizhanjie1314** [jeneser/douban#12]

**Comment by lizhanjie1314** [comment]
![Uploading S6C`D[I1GIYJ2Q%2MW(7HQV.png…]()

**Comment by jeneser** [comment]
Hello, thanks for opening an issue with me.
Can you give me more information?😀

**Comment by lizhanjie1314** [comment]
执行 npm run dev  报错了
$ npm run dev
> douban@1.0.0 dev E:\node\douban
> node build/dev-server.js

 ERROR  Failed to compile with 1 errors14:02:52

 error  in ./src/main.js

Module build failed: Error: Cannot find module 'fs.realpath'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\node\douban\node_modules\shelljs\node_modules\glob         \glob.js:44:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (E:\node\douban\node_modules\shelljs\src\common.js:7:1         2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8086

**Comment by jeneser** [comment]
Hi,😃
Firstly, please check the node env (NODE_PATH)
Secondly, Enter `/douban` directory. Remove `node_modules`, then using `npm install` **Reinstall** the dependencies.
Try again.
