### ISSUE TITLE
构建不成功

### ISSUE THREAD

**Issue by fredshare** [jeneser/douban#13]
> douban@1.0.0 dev /Users/sharexie/Documents/project/vuedemo/douban-master
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (/Users/sharexie/Documents/project/vuedemo/douban-master/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/sharexie/Documents/project/vuedemo/douban-master/build/dev-server.js:71:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.8.1/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! douban@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the douban@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the douban package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs douban
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls douban
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sharexie/Documents/project/vuedemo/douban-master/npm-debug.log

麻烦看下这是什么问题

**Comment by jeneser** [comment]
Thanks for opening an issue with me.😀
There could be port conflicts.Please close the associated application or change the port number.
