### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by keling689** [jeneser/douban#33]
error  in ./src/main.js

Module build failed: Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\web前端\github项目集\douban\node_modules\_babel-core@6.26.3@babel-core\lib\transformation\file\index.js:6:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\web前端\github项目集\douban\node_modules\_babel-core@6.26.3@babel-core\lib\api\node.js:6:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

 @ multi ./build/dev-client ./src/main.js

**Comment by Moonofweisheng** [comment]
先执行一下 npm i再执行npm run dev

**Comment by keling689** [comment]
执行npm i 了之后报的

**Comment by liujianfe** [comment]
打开有package-lock.json文件的文件夹的douban-master 试试
